[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB

board_build.arduino.memory_type = qio_opi

lib_deps =
    https://github.com/eclipse-zenoh/zenoh-pico
    https://github.com/eProsima/Micro-CDR
    https://github.com/tzapu/WiFiManager.git
    https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library

build_flags =
    -I include
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0